name: Build README

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '30 4 * * *'

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: |
          npm ci
      - name: Update README
        run: |-
          npm start
          cat README.md
      - name: Commit and push if changed
        run: |-
          git add .
          git diff
          git config --global user.email "github-action-bot@example.com"
          git config --global user.name "GitHub Action Bot"
          git commit -m "docs(README): update README" -a || echo "No changes to commit"
          git push